### ISSUE TITLE
nix-build error on macos

### ISSUE THREAD

**Issue by amichalu** [PacktPublishing/Hands-On-Software-Architecture-with-Cpp#51]
Hi, looks like nix-build on macos generates:

`error: Package ‘lsb_release’ in /nix/store/6gyh8gqb20hn0xnz5a2rifhncnzwicmb-source/pkgs/os-specific/linux/lsb-release/default.nix:16 is not supported on ‘x86_64-darwin’, refusing to evaluate.`

any workaround ?

**Comment by DoomHammer** [comment]
Hi! Indeed, this package won't be found on Mac. For a short workaround you can try deleting this line as the binaries are probably not needed anyway. I'll see if there's a way to fix this permanently as well.

**Comment by DoomHammer** [comment]
@amichalu , can you check https://github.com/PacktPublishing/Software-Architecture-with-Cpp/pull/52 if it works for you?

**Comment by amichalu** [comment]
It's another error as a result of **nix-build**:

This derivation is not meant to be built, aborting

```
error: builder for '/nix/store/7895cas1dyia813sqsd67nkidj170nw1-nix-shell.drv' failed with exit code 1;
       last 4 log lines:
       > nobuildPhase
       >
       > This derivation is not meant to be built, aborting
       >
       For full logs, run 'nix log /nix/store/7895cas1dyia813sqsd67nkidj170nw1-nix-shell.drv'.
```
mentioned log contents:

`error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override`

**Comment by DoomHammer** [comment]
Can you give more background into:
- which architecture are you running: Intel or M1?
- what is the OS version?
- what is the Nix version?

**Comment by amichalu** [comment]
**Nix:**
`√ ~ % nix-env --version`
`nix-env (Nix) 2.6.0`

installation verified according to nixos.org doc

**macos:**
`ProductName:	Mac OS X`
`ProductVersion:	10.15.7`
`BuildVersion:	19H1615`

**apple Intel**

**Comment by DoomHammer** [comment]
Thanks! I'll check this after the weekend and see if I can help.

**Comment by DoomHammer** [comment]
Testing it on 10.15.7 here on Intel as well.

Are you using the `direnv allow` method or opening `nix-shell` directly?
