### ISSUE TITLE
**Could not find a package configuration file provided by "Microsoft.GSL"**

### ISSUE THREAD

**Issue by briviere** [PacktPublishing/Hands-On-Software-Architecture-with-Cpp#56]
I'm getting the following error when trying to build the Chapter02 example:

**Could not find a package configuration file provided by "Microsoft.GSL"**

With the following profile:

conan profile show
Host profile:
[settings]
arch=x86_64
build_type=Release
compiler=clang
compiler.cppstd=gnu14
compiler.libcxx=libc++
compiler.version=11
os=Macos

Build profile:
[settings]
arch=x86_64
build_type=Release
compiler=clang
compiler.cppstd=gnu14
compiler.libcxx=libc++
compiler.version=11
os=Macos

CMake Error at CMakeLists.txt:14 (find_package):
  Could not find a package configuration file provided by "Microsoft.GSL"
  with any of the following names:

    Microsoft.GSLConfig.cmake
    microsoft.gsl-config.cmake

  Add the installation prefix of "Microsoft.GSL" to CMAKE_PREFIX_PATH or set
  "Microsoft.GSL_DIR" to a directory containing one of the above files.  If
  "Microsoft.GSL" provides a separate development package or SDK, be sure it
  has been installed.

**Comment by briviere** [comment]
I resolved my issue by adding the following

include(FetchContent)

FetchContent_Declare(GSL
    GIT_REPOSITORY "https://github.com/microsoft/GSL"
    GIT_TAG "v4.0.0"
    GIT_SHALLOW ON
)

FetchContent_MakeAvailable(GSL)

**Comment by JaylonGu** [comment]
Changing CMakeLists.txt  as following can work
```
- list(APPEND CMAKE_PREFIX_PATH "${CMAKE_BINARY_DIR}")
+ list(APPEND CMAKE_PREFIX_PATH "${CMAKE_SOURCE_DIR}")
```

or running conan command as following 
```
conan install .. --output-folder=. --build=missing -s build_type=Release -pr=sacpp
```
instead of
```
conan install .. --build=missing -s build_type=Release -pr=sacpp
```
can also work
